### ISSUE TITLE
Program main

### ISSUE THREAD

**Issue by mszreder** [mcjczapiewski/daoHomework#1]
DatabaseConnection.ImportVehiclesFromDatabase();
            IVehicleDao vehicleDao = new VehicleDaoImpl();
First mentioned line shouldbe internal detial of the concreet database dao implementation.
Always think is such way - can you replace existing dao with other dao without a signle chnage in code which use it ?

**Comment by mcjczapiewski** [comment]
Line moved to VehicleDaoImpl to DeleteVehicle and UpdateMaxPassengersNumber methods.
