### ISSUE TITLE
VehicleDaoImpl GetAllVehicles return static list content

### ISSUE THREAD

**Issue by mszreder** [mcjczapiewski/daoHomework#2]
get all vehicles returns content of static list why then field Vehicles is publick as well ?
There should be only one way of retieval of vehicles - through method as only get method is defined in interface

**Comment by mcjczapiewski** [comment]
vehicles list changed to private,  new HevicleDaoImpl instance in DatabaseConnection, new AddVehicle method in IVehicleDao, to import vehicles from database
