### ISSUE TITLE
unclear purpose of DatabaseConnection

### ISSUE THREAD

**Issue by mszreder** [mcjczapiewski/daoHomework#3]
some part of sql is in daoimpl some part in databaseconnection and when it also creates vehicles.

The dependency and usage direction should look as follows:
Program uses IDaoInterface 
IDAoInterface is implemented by ConcreteDao Implementation which uses DatabaseConnection to execute query and establish connection.

**Comment by mcjczapiewski** [comment]
SQL querries moved to new methods in DatabaseConnection
